version: '2'
services:
  otrs:
    build: .
    ports:
     - "80:80"
    depends_on:
     - mysql
    volumes_from:
     - mysql
  mysql:
    image: mysql
    volumes:
     - /etc/mysql
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "g,XR^tPwa7j"
      MYSQL_PASSWORD: "g,XR^tPwa7j"
